name : Expense Tracker CI

on:
    push:
        branches:
        - main
    
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      # 7. Build backend Docker image
      - name: Build backend Docker image
        run: docker build -t leasony/expense-tracker-backend:latest ./backend

      # 8. Build frontend Docker image
      - name: Build frontend Docker image
        run: docker build --build-arg VITE_API_URL=https://expense-tracker-backend-latest-viwx.onrender.com/api -t leasony/expense-tracker-frontend:latest ./frontend

      # 9. Push backend image
      - name: Push backend Docker image
        run: docker push leasony/expense-tracker-backend:latest

      # 10. Push frontend image
      - name: Push frontend Docker image
        run: docker push leasony/expense-tracker-frontend:latest

      - name: Trigger Render deployment
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK  }}"
